#port: "/dev/ttyUSB0"
port: "COM3"
protocol: "KW"
description: "VPlusHO1"
schedule:
  enabled: true
  cronInMinutes: 15
database:
  enabled: false
  url: ""
  user: ""
  password: ""
  retention: "365d"
  dbname: ""
  